INSERT INTO producto (nombre, descripcion, precio, stock, id_categoria, imagen) VALUES
('Alfombrilla ergonomica', 'Alfombrilla para raton ergonomica', 3.00, 100, 1, ''),
('Archivador', 'Archivador estandar', 4.00, 50, 1, ''),
('Archivador negro', 'Archivador color negro', 4.50, 50, 1, ''),
('Bandeja de color', 'Bandeja organizadora de colores', 4.20, 30, 1, ''),
('Bandeja fija', 'Bandeja fija para escritorio', 5.20, 30, 1, ''),
('Boligrafos de colores', 'Set de boligrafos multicolor', 1.50, 200, 1, ''),
('Camiseta con logo', 'Camiseta corporativa con logo', 15.00, 20, 1, ''),
('Calculadora cientifica', 'Calculadora avanzada para calculos', 12.00, 15, 2, ''),
('Calculadora especial', 'Calculadora con funciones especiales', 15.00, 10, 2, ''),
('Clip caja', 'Caja de clips metalicos', 2.30, 100, 1, ''),
('Clip colores', 'Clips de colores surtidos', 2.70, 100, 1, ''),
('Folios de colores', 'Paquete de folios de colores', 6.00, 50, 1, ''),
('Folios personalizados', 'Folios con diseño personalizado', 7.00, 50, 1, ''),
('Folios reciclaje', 'Folios reciclados', 6.00, 50, 1, ''),
('Grapadora manual', 'Grapadora manual básica', 13.60, 20, 1, ''),
('Grapadora metalica', 'Grapadora metalica resistente', 20.30, 15, 1, ''),
('Lapices Staedtler', 'Set de lapices Staedtler', 2.00, 100, 1, ''),
('Portalapices con reloj', 'Portalapices con reloj incorporado', 10.00, 25, 1, ''),
('Portalapices serigrafiado', 'Portalapices con serigrafia', 6.00, 25, 1, ''),
('Post-it colores', 'Notas adhesivas de colores', 3.00, 100, 1, ''),
('Post-it unico color', 'Notas adhesivas de un solo color', 2.50, 100, 1, ''),
('Sobres 90 G/M2', 'Sobres estandar 90 gramos', 2.50, 100, 1, ''),
('Subrayador de colores', 'Set de subrayadores multicolor', 9.00, 50, 1, ''),
('Subrayador unico color', 'Subrayador color unico', 2.20, 50, 1, ''),
('USB Expedit', 'Memoria USB Expedit', 7.00, 30, 2, ''),
('USB 16 GB', 'Memoria USB 16 GB', 9.24, 30, 2, ''),
('Agendas Zeppelin', 'Agenda corporativa Zeppelin', 15.00, 20, 1, ''),
('Portaminas Pilot 05', 'Portaminas Pilot 0.5 mm', 1.50, 50, 1, ''),
('Libreta con logo', 'Libreta corporativa con logo', 4.00, 50, 1, ''),
('Aire acondicionado Fijo Aire Plus 3x1', 'Equipo de aire acondicionado', 825.61, 5, 2, ''),
('ALEX comoda con 9 cajones', 'Comoda ALEX con 9 cajones', 106.61, 10, 3, ''),
('Cubo pedal 40 litros CURVER CROMADO MATE', 'Cubo de basura cromado', 25.57, 15, 4, ''),
('Estanteria de resina ELEGANCE NEGRO 138x60x30', 'Estanteria resistente', 66.00, 10, 3, ''),
('M-Cajonera', 'Cajonera metalica', 66.00, 10, 3, ''),
('Mesas de dirección H2 de Herpesa', 'Mesa de direccion elegante', 147.00, 5, 3, ''),
('Nespresso De Longhi Inissia', 'Cafetera Nespresso', 61.61, 10, 2, ''),
('Pantalla con trípode FONESTAR', 'Pantalla para proyector', 128.09, 5, 2, ''),
('Pantalla Retina 4K Procesador a 3 GHz 1 TB', 'Pantalla Retina 4K con procesador', 1244.30, 2, 2, ''),
('Reposapies Bultrupudos', 'Reposapies ergonomico', 28.00, 10, 4, ''),
('Silla de escritorio Nelf', 'Silla ergonomica para oficina', 60.00, 10, 3, ''),
('Soporte negro', 'Soporte para monitor negro', 3.50, 20, 4, ''),
('VISCHAN Reloj de pared', 'Reloj de pared elegante', 12.39, 15, 4, ''),
('Lampara Flexo plateado', 'Lampara de escritorio plateada', 12.50, 15, 4, '');